
// Generated by Cadence Genus(TM) Synthesis Solution 21.17-s066_1
// Generated on: Apr 10 2025 20:32:44 EDT (Apr 11 2025 00:32:44 UTC)

// Verification Directory fv/alu_1bit 

module arithmetic_unit(Ai, Bi, Cin, S0, S1, Di, Cout);
  input Ai, Bi, Cin, S0, S1;
  output Di, Cout;
  wire Ai, Bi, Cin, S0, S1;
  wire Di, Cout;
  wire n_0;
  ADDFX1 g188__2398(.A (Ai), .B (Cin), .CI (n_0), .CO (Cout), .S (Di));
  MX2XL g189__5107(.A (S1), .B (S0), .S0 (Bi), .Y (n_0));
endmodule

module alu_1bit(Ai, Bi, Ai_minus_1, Ai_plus_1, Cin, S0, S1, S2, S3, Fi,
     Cout);
  input Ai, Bi, Ai_minus_1, Ai_plus_1, Cin, S0, S1, S2, S3;
  output Fi, Cout;
  wire Ai, Bi, Ai_minus_1, Ai_plus_1, Cin, S0, S1, S2, S3;
  wire Fi, Cout;
  wire Di, arithmetic_cout, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  arithmetic_unit arithmetic_unit_inst(.Ai (Ai), .Bi (Bi), .Cin (Cin),
       .S0 (S0), .S1 (S1), .Di (Di), .Cout (arithmetic_cout));
  CLKMX2X12 g443__6260(.A (n_11), .B (n_5), .S0 (S3), .Y (n_12));
  MX2XL g444__4319(.A (Di), .B (n_10), .S0 (S2), .Y (n_11));
  OAI31X1 g445__8428(.A0 (n_2), .A1 (n_4), .A2 (n_3), .B0 (n_9), .Y
       (n_10));
  AOI32X1 g447__5526(.A0 (S0), .A1 (Bi), .A2 (n_1), .B0 (n_3), .B1
       (n_4), .Y (n_9));
  NOR2X1 g448__6783(.A (S3), .B (n_7), .Y (n_8));
  NAND2X1 g449__3680(.A (n_6), .B (arithmetic_cout), .Y (n_7));
  NAND3X1 g450__1617(.A (Cin), .B (S0), .C (S1), .Y (n_6));
  MX2XL g451__2802(.A (Ai_minus_1), .B (Ai_plus_1), .S0 (S2), .Y (n_5));
  NOR2X1 g452__1705(.A (S0), .B (Bi), .Y (n_4));
  NOR2X1 g453__5122(.A (S1), .B (Ai), .Y (n_2));
  AND2X1 g454__8246(.A (Ai), .B (S1), .Y (n_3));
  INVX1 g455(.A (Ai), .Y (n_1));
  CLKBUFX20 drc_bufs(.A (n_0), .Y (Cout));
  CLKBUFX20 drc_bufs457(.A (n_12), .Y (Fi));
  NOR2BX1 g2__7098(.AN (n_8), .B (S2), .Y (n_0));
endmodule

